### ISSUE TITLE
Don't save color settings with dark mode, when restart app

### ISSUE THREAD

**Issue by redian23** [alainm23/byte#42]
## Step 1
Select green theme 
![Screenshot from 2019-09-13 22-58-09](https://user-images.githubusercontent.com/46902231/64909832-9aa26900-d719-11e9-9c62-a964e6a9123f.png)
## Step 2
Restart app 
## Step 3 
Again red color, but in setting on green color 
![Screenshot from 2019-09-13 21-57-00](https://user-images.githubusercontent.com/46902231/64909859-d0dfe880-d719-11e9-8066-4a39523e726d.png)
![Screenshot from 2019-09-14 18-03-18](https://user-images.githubusercontent.com/46902231/64909873-f3720180-d719-11e9-88c6-bff5b385c2f2.png)

**Comment by alainm23** [comment]
Thanks for the PR friend, I did this behavior intentionally because I found it a little difficult to handle the issues with the dark mode activated.

To solve this problem I plan to eliminate the dark mode and play with the themes. For example, the green theme I send looks great with the dark mode on but not with the normal mode.

**Comment by redian23** [comment]
And one thing.
When open setting with dark mode, colors can be chosen. But when relaunch dark mode, select colors don't work.
Maybe it is one bug.
I will wait fix.
